from setuptools import setup, find_packages

setup(
    name="time_series_forecasting",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "streamlit>=1.24.0",
        "pandas>=1.5.0",
        "numpy>=1.23.0",
        "scikit-learn>=1.0.0",
        "tensorflow>=2.12.0",
        "matplotlib>=3.5.0",
        "seaborn>=0.12.0",
        "statsmodels>=0.13.0",
        "pmdarima>=2.0.0",
        "xgboost>=1.7.0",
        "plotly>=5.13.0",
        "scipy>=1.9.0",
    ],
    author="Your Team Name",
    author_email="your.email@example.com",
    description="A Streamlit application for time series forecasting using various models",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/time-series-forecasting",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
    python_requires=">=3.8",
)